name: Reusable Deploy
on: workflow_call
  inputs: 
    artifact-name:
      description: The name of the deployable artifact files
      required: false
      default: dist-files
      type: string    
  outputs:
    result:
      description: Result of the deployment operation
      value: ${{ jobs.deploy.outputs.job-result }}      
  # secrets:
  #   some-secret:
  #     required: true      
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs: 
      job-result: ${{ steps.set-result.outputs.step-result }}    
    steps:
      - name: Get code
        uses: actions/download-artifact@v3  
        with: 
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls              
      - name: Output information
        run: echo "Deploying..."
      - name: Set result output
        id: set-result
        run: echo 'step-result=success' >> $GITHUB_OUTPUT
